apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::115274531114:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6RGMM48XBX23
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::115274531114:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-16T23:45:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1684"
  uid: c1017ce9-fcef-4331-bb37-2bcf635f4bde