apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::720567747027:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EGH8CT6ZM04R
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
       - system:masters
       rolearn: arn:aws:iam::720567747027:role/UdacityFlaskDeployCBKubectlRole
       username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-06T00:02:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1658"
  uid: 36666bac-8359-4149-8ffa-6d9286853e7f
